//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.CustomPlugins.Bot.Rin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiSteamFarm.CustomPlugins.Rin.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /code Github 开源项目链接：https://github.com/chitsanfei/rin-asf-bot
        ///在您使用该开源机器人时，请必须知悉本机器人并不收集任何用户信息，本机器人并未储存任何图片，本机器人使用的所有API均为第三方，作者不能控制或审计相关内容，本机器人仅供技术交流。请务必遵守您所在的相关法律使用。
        ///任何人员可以通过 Github 审查相关代码，并提出意见和改进。.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pre 欢迎您使用 RinBot 呢，茫茫人海相遇可是一种缘分～
        ///输入下列指令获得相应功能：
        ///!setu: 获取一张色图
        ///    |- 允许参数: !setu [参数] 获取多张色图（如：!setu 2）
        ///!r18: 获取限制的色图
        ///    |- 允许参数: !r18 [参数] 获取多张色图（如：!r18 2）
        ///!anime: 获取一张相对正常的二次元图片
        ///!cat: 获取随机的猫猫图（ASF官方例程）
        ///!abt: 本机器人的关于说明
        ///!h: 本机器人的菜单.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: Rin现在正在进行加载过程，测试版本为.
        /// </summary>
        internal static string InitNotice {
            get {
                return ResourceManager.GetString("InitNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: 这是一个不稳定的构建！.
        /// </summary>
        internal static string InitProgramUnstable {
            get {
                return ResourceManager.GetString("InitProgramUnstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: 欢迎您！Rin已经被ASF主程序侦测到并装载了，接下来需要进入加载过程！.
        /// </summary>
        internal static string InitRinLoaded {
            get {
                return ResourceManager.GetString("InitRinLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.1.4.3.
        /// </summary>
        internal static string VersionASF {
            get {
                return ResourceManager.GetString("VersionASF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2025/4/11.
        /// </summary>
        internal static string VersionDate {
            get {
                return ResourceManager.GetString("VersionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.9.0.
        /// </summary>
        internal static string VersionPlugin {
            get {
                return ResourceManager.GetString("VersionPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有获取到二次元图片，或中途出现了意外。.
        /// </summary>
        internal static string WarningAnimePicLost {
            get {
                return ResourceManager.GetString("WarningAnimePicLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: Rin掉线了哦！ASF主程序将尝试自动重连！.
        /// </summary>
        internal static string WarningBotDisconnected {
            get {
                return ResourceManager.GetString("WarningBotDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不好！好像猫猫走丢了哦！QAQ.
        /// </summary>
        internal static string WarningCatLost {
            get {
                return ResourceManager.GetString("WarningCatLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好像没有对应的指令?输入「!h」可以查看可以使用的指令。.
        /// </summary>
        internal static string WarningNoCommand {
            get {
                return ResourceManager.GetString("WarningNoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对不起！你的权限不够哟！:3.
        /// </summary>
        internal static string WarningNoPermission {
            get {
                return ResourceManager.GetString("WarningNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您设置的参数是非法参数！.
        /// </summary>
        internal static string WarningParamIllegal {
            get {
                return ResourceManager.GetString("WarningParamIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您设置的参数超出了限制！.
        /// </summary>
        internal static string WarningParamOutrage {
            get {
                return ResourceManager.GetString("WarningParamOutrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您已经触发请求上限，请休息一下！.
        /// </summary>
        internal static string WarningRateLimit {
            get {
                return ResourceManager.GetString("WarningRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到相应的内容或者内容呢丢失了！QAQ.
        /// </summary>
        internal static string WarningSetuLost {
            get {
                return ResourceManager.GetString("WarningSetuLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rin侦测到可能的一条链接哦！诈骗多发，请务必警惕陌生链接，网页千万条安全第一条。不要输入自己的任何账号密码，泄漏财产信息哦！！！.
        /// </summary>
        internal static string WarningWebLink {
            get {
                return ResourceManager.GetString("WarningWebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行流出现了错误，触发区域并没有设置异常抛出，请联系开发者获取支持。
        ///        发生在方法体：.
        /// </summary>
        internal static string WarningWorkflow {
            get {
                return ResourceManager.GetString("WarningWorkflow", resourceCulture);
            }
        }
    }
}
