//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.CustomPlugins.Bot.Rin.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ArchiSteamFarm.CustomPlugins.Bot.Rin.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DebugASFVersion {
            get {
                return ResourceManager.GetString("DebugASFVersion", resourceCulture);
            }
        }
        
        internal static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        internal static string LastEditedTime {
            get {
                return ResourceManager.GetString("LastEditedTime", resourceCulture);
            }
        }
        
        internal static string InitWarning {
            get {
                return ResourceManager.GetString("InitWarning", resourceCulture);
            }
        }
        
        internal static string InitProgramUnstableWarning {
            get {
                return ResourceManager.GetString("InitProgramUnstableWarning", resourceCulture);
            }
        }
        
        internal static string OnRinLoaded {
            get {
                return ResourceManager.GetString("OnRinLoaded", resourceCulture);
            }
        }
        
        internal static string BotDisconnectedWarning {
            get {
                return ResourceManager.GetString("BotDisconnectedWarning", resourceCulture);
            }
        }
        
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        internal static string SetuNotFound {
            get {
                return ResourceManager.GetString("SetuNotFound", resourceCulture);
            }
        }
        
        internal static string HitokotoNotFound {
            get {
                return ResourceManager.GetString("HitokotoNotFound", resourceCulture);
            }
        }
        
        internal static string CatNotFoundOrLost {
            get {
                return ResourceManager.GetString("CatNotFoundOrLost", resourceCulture);
            }
        }
        
        internal static string NoPermissionWarning {
            get {
                return ResourceManager.GetString("NoPermissionWarning", resourceCulture);
            }
        }
        
        internal static string OutOfOrderList {
            get {
                return ResourceManager.GetString("OutOfOrderList", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string WebLinkWarning {
            get {
                return ResourceManager.GetString("WebLinkWarning", resourceCulture);
            }
        }
        
        internal static string SuicideWarning {
            get {
                return ResourceManager.GetString("SuicideWarning", resourceCulture);
            }
        }
        
        internal static string DogNotFoundOrLost {
            get {
                return ResourceManager.GetString("DogNotFoundOrLost", resourceCulture);
            }
        }
        
        internal static string AnimePicNotFound {
            get {
                return ResourceManager.GetString("AnimePicNotFound", resourceCulture);
            }
        }
    }
}
