//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.CustomPlugins.Bot.Rin.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ArchiSteamFarm.CustomPlugins.Rin.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string VersionASF {
            get {
                return ResourceManager.GetString("VersionASF", resourceCulture);
            }
        }
        
        internal static string VersionPlugin {
            get {
                return ResourceManager.GetString("VersionPlugin", resourceCulture);
            }
        }
        
        internal static string VersionDate {
            get {
                return ResourceManager.GetString("VersionDate", resourceCulture);
            }
        }
        
        internal static string InitNotice {
            get {
                return ResourceManager.GetString("InitNotice", resourceCulture);
            }
        }
        
        internal static string InitProgramUnstable {
            get {
                return ResourceManager.GetString("InitProgramUnstable", resourceCulture);
            }
        }
        
        internal static string InitRinLoaded {
            get {
                return ResourceManager.GetString("InitRinLoaded", resourceCulture);
            }
        }
        
        internal static string WarningBotDisconnected {
            get {
                return ResourceManager.GetString("WarningBotDisconnected", resourceCulture);
            }
        }
        
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        internal static string WarningSetuLost {
            get {
                return ResourceManager.GetString("WarningSetuLost", resourceCulture);
            }
        }
        
        internal static string WarningHitokotoLost {
            get {
                return ResourceManager.GetString("WarningHitokotoLost", resourceCulture);
            }
        }
        
        internal static string WarningCatLost {
            get {
                return ResourceManager.GetString("WarningCatLost", resourceCulture);
            }
        }
        
        internal static string WarningNoPermission {
            get {
                return ResourceManager.GetString("WarningNoPermission", resourceCulture);
            }
        }
        
        internal static string WarningNoCommand {
            get {
                return ResourceManager.GetString("WarningNoCommand", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string WarningWebLink {
            get {
                return ResourceManager.GetString("WarningWebLink", resourceCulture);
            }
        }
        
        internal static string WarningDogLost {
            get {
                return ResourceManager.GetString("WarningDogLost", resourceCulture);
            }
        }
        
        internal static string WarningAnimePicLost {
            get {
                return ResourceManager.GetString("WarningAnimePicLost", resourceCulture);
            }
        }
        
        internal static string WarningRateLimit {
            get {
                return ResourceManager.GetString("WarningRateLimit", resourceCulture);
            }
        }
    }
}
