//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.CustomPlugins.Bot.Rin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiSteamFarm.CustomPlugins.Bot.Rin.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /code Github开源项目链接：https://github.com/ShizukuWorld/rin-asf-bot \n分支开发作者Steam：https://steamcommunity.com/id/mrmarketsama/.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: Rin掉线了哦！ASF主程序将尝试自动重连！.
        /// </summary>
        internal static string BotDisconnectedWarning {
            get {
                return ResourceManager.GetString("BotDisconnectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不好！好像猫猫走丢了哦！QAQ.
        /// </summary>
        internal static string CatNotFoundOrLost {
            get {
                return ResourceManager.GetString("CatNotFoundOrLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.2.8.3.
        /// </summary>
        internal static string DebugASFVersion {
            get {
                return ResourceManager.GetString("DebugASFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pre 欢迎您使用RinBot呢，茫茫人海相遇可是一种缘分～\n本拉胯Bot的分支设计者:MashiroSAMAowo\n输入下列指令获得相应功能：\n!setu:获取一张色图\n!r18:获取限制的色图（已被限制仅高权限使用）\n!hito:获取一句一言\n!cat:获取随机的猫猫图（ASF官方例程）\n!abt:寻找关于这个bot的一切，包括到底是哪个憨批作者写出来的！.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好像一言走丢了哦！QAQ.
        /// </summary>
        internal static string HitokotoNotFound {
            get {
                return ResourceManager.GetString("HitokotoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: 这是一个不稳定的构建！.
        /// </summary>
        internal static string InitProgramUnstableWarning {
            get {
                return ResourceManager.GetString("InitProgramUnstableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: Rin现在正在进行加载过程，测试版本为.
        /// </summary>
        internal static string InitWarning {
            get {
                return ResourceManager.GetString("InitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022.8.2.
        /// </summary>
        internal static string LastEditedTime {
            get {
                return ResourceManager.GetString("LastEditedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对不起！你的权限不够哟！:3.
        /// </summary>
        internal static string NoPermissionWarning {
            get {
                return ResourceManager.GetString("NoPermissionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RinBotPlugin: 欢迎您！Rin已经被ASF主程序侦测到并装载了，接下来需要进入加载过程！.
        /// </summary>
        internal static string OnRinLoaded {
            get {
                return ResourceManager.GetString("OnRinLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好像没有对应的指令?输入「!h」可以查看可以使用的指令。.
        /// </summary>
        internal static string OutOfOrderList {
            get {
                return ResourceManager.GetString("OutOfOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.2.
        /// </summary>
        internal static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到相应的内容或者内容呢丢失了！QAQ.
        /// </summary>
        internal static string SetuNotFound {
            get {
                return ResourceManager.GetString("SetuNotFound", resourceCulture);
            }
        }
    }
}
